### ISSUE TITLE
JSON property "timespent" must not be NULL

### ISSUE THREAD

**Issue by mikt** [lesstif/php-jira-rest-client#100]
Hi,

Just downloaded this library, and tried to pull in one of my test issues, and got the following error:

```
[2017-12-21 18:07:11] dev.ERROR: exception 'JsonMapper_Exception' with message 'JSON property "timespent" must not be NULL' in /var/www/html/gm-sbt/vendor/netresearch/jsonmapper/src/JsonMapper.php:183
Stack trace:
#0 /var/www/html/gm-sbt/vendor/netresearch/jsonmapper/src/JsonMapper.php(258): JsonMapper->map(Object(stdClass), Object(JiraRestApi\Issue\IssueField))
#1 /var/www/html/gm-sbt/vendor/lesstif/php-jira-rest-client/src/Issue/IssueService.php(24): JsonMapper->map(Object(stdClass), Object(JiraRestApi\Issue\Issue))
#2 /var/www/html/gm-sbt/domains/models/jira/ActivityFreezeModel.php(14): JiraRestApi\Issue\IssueService->get('10001')
```

Timespent is not something that is used in my business process flows :/

Using version 1.5.*

**Comment by lesstif** [comment]
this issue fixed v1.14.2.

thanks
