### ISSUE TITLE
400 Error

### ISSUE THREAD

**Issue by MikeyObviously** [lesstif/php-jira-rest-client#136]
Hello,

I'm getting a 400 error, and I can't figure out why. Code and error to follow:

`<?php 
set_time_limit(720);
require '../../eds-binaries/php/php5619vc11x86x170214141849/vendor/autoload.php';

use JiraRestApi\Project\ProjectService;
use JiraRestApi\Issue\IssueService;
use JiraRestApi\Issue\IssueField;
use JiraRestApi\Issue\Comment;
use JiraRestApi\JiraException;

$jql = 'project = DIG AND issuetype = "Product Transmittal" AND status in ("In Production", QA, "Content Development")';

$issueService = new IssueService();
$ret = $issueService->search($jql, 0, 10);

foreach($ret->issues as $issue){
	$issueKey = $issue->key;
	$issueField = new IssueField();
	$s = [];
	array_push($s, $issue->fields->customfield_11345);
	$issueField->addCustomField('customfield_10850', "12345");
	$ret = $issueService->update($issueKey, $issueField);
}
?>`

"Fatal error: Uncaught exception 'JiraRestApi\JiraException' with message 'CURL HTTP Request Failed: Status Code : 400, URL:https://jira.cengage.com//rest/api/2/issue/DIG-50773? Error Message : {"errorMessages":[],"errors":{"issuetype":"Can not deserialize instance of com.atlassian.jira.rest.api.issue.ResourceRef out of START_ARRAY token\n at [Source: N/A; line: -1, column: -1]","project":"Could not find project by id or key."}}' in C:\Program Files (x86)\EasyPHP\eds-binaries\php\php5619vc11x86x170214141849\vendor\lesstif\php-jira-rest-client\src\JiraClient.php:212 Stack trace: #0 C:\Program Files (x86)\EasyPHP\eds-binaries\php\php5619vc11x86x170214141849\vendor\lesstif\php-jira-rest-client\src\Issue\IssueService.php(181): JiraRestApi\JiraClient->exec('/issue/DIG-5077...', '{"fields":{"iss...', 'PUT') #1 C:\Program Files (x86)\EasyPHP\eds-www\jira\epic.php(30): JiraRestApi\Issue\IssueService->update('DIG-50773', Object(JiraRestApi\Issue\IssueField)) #2 {main} thrown in C:\Program Files (x86)\EasyPHP\eds-binaries\php\php5619vc11x86x170214141849\vendor\lesstif\php-jira-rest-client\src\JiraClient.php on line 212"

**Comment by lesstif** [comment]
hi.

i found an error message in the error stack.

```code
Could not find project by id or key."
```

could you check this point.

- check user have right permission for access DIG-50773 issue. (check also issue security scheme)

thanks.
